import type { VerificationResult } from '../types';

/**
 * Formats a clean, structured plain-text representation of the official PRGI Title Verification Memorandum.
 * Suitable for pasting into official email correspondence, statutory case dockets, or legal archives.
 */
export function formatMemorandumPlainText(result: VerificationResult): string {
  const line = '================================================================================';
  const subLine = '--------------------------------------------------------------------------------';
  const timestamp = result.timestamp || new Date().toISOString();

  const clashingRows =
    result.clashingTitles.length > 0
      ? result.clashingTitles
          .map((c, i) => {
            return `  [${i + 1}] ${c.title} (Reg: ${c.regNo || 'N/A'})
      Jurisdiction : ${c.state || 'National'} | Language: ${c.language || 'English'}
      Clash Type   : ${c.matchType} | Similarity: ${c.similarity}%
      Statutory Note: ${c.reason}`;
          })
          .join('\n\n')
      : '  (No conflicting registered titles detected within threshold)';

  const rulesRows =
    result.ruleViolations.length > 0
      ? result.ruleViolations
          .map((r) => {
            const status = r.passed ? 'PASSED' : `FAILED [${r.severity}]`;
            return `  * [${r.ruleId}] ${r.ruleName}: ${status}
    Clause : ${r.clause}
    Details: ${r.description}${r.triggerPhrase ? ` (Trigger: "${r.triggerPhrase}")` : ''}`;
          })
          .join('\n\n')
      : '  (All statutory baseline checks passed)';

  return `${line}
PRESS REGISTRAR GENERAL OF INDIA (PRGI)
Ministry of Information and Broadcasting, Government of India
TITLE VERIFICATION AUDIT MEMORANDUM
${line}

CASE & VERIFICATION METADATA:
  Proposed Title       : "${result.inputTitle}"
  Normalized / Script  : "${result.normalizedTitle}" (${result.detectedLanguage || 'English'})
  Transliterated Roman : "${result.transliteratedTitle || result.normalizedTitle}"
  Audit Timestamp (UTC): ${timestamp}
  Processing Latency   : ${result.processingTimeMs} ms

${subLine}
STATUTORY VERDICT & COMPOSITE RISK:
${subLine}
  Verdict Status       : ${result.verdict}
  Conflict Risk Score  : ${result.verdictScore} / 100
  Verdict Summary      : ${
    result.verdict === 'APPROVED'
      ? 'APPROVED - CLEAR FOR REGISTRATION'
      : result.verdict === 'REJECTED'
      ? 'REJECTED - STATUTORY VIOLATION / HIGH CONFLICT'
      : 'MANUAL REVIEW REQUIRED - BORDERLINE AMBER RISK'
  }

${subLine}
4-DIMENSIONAL NLP SIMILARITY SUB-SCORES:
${subLine}
  1. Lexical & Anagram Score     : ${result.similarityBreakdown.lexicalScore}%
  2. Phonetic Soundex Score      : ${result.similarityBreakdown.phoneticScore}%
  3. Semantic Cross-Lingual Score: ${result.similarityBreakdown.semanticScore}%
  4. Core-Word Distinctive Clash : ${result.similarityBreakdown.coreWordScore}%
  5. Composite Blended Score     : ${result.similarityBreakdown.blendedScore}%
  Extracted Distinctive Tokens   : [${result.coreWords.join(', ')}]

${subLine}
TOP REGISTERED CONFLICT CLASHES:
${subLine}
${clashingRows}

${subLine}
STATUTORY GUIDELINES & RULEBOOK AUDIT:
${subLine}
${rulesRows}

${subLine}
PLAIN-LANGUAGE EXPLANATION & GUIDANCE:
${subLine}
  Explanation:
  ${result.explanation}

  Recommended Guidance:
  ${result.recommendedAction}

${line}
DISCLAIMER & LEGAL DETERMINATION NOTICE:
This document is an automated decision-support audit recommendation generated by the
PRGI TitleGuard verification system pursuant to the Press and Registration of
Periodicals (PRP) Act 2023. This memorandum does not constitute a final legal title
allocation until formally signed by the authorized PRGI Registrar or District Magistrate.
${line}`;
}
