#!/usr/bin/env python3
"""
scripts/rule_coverage.py
------------------------
Prints a human-readable coverage summary and updates rules/coverage.md.

OUTPUT FORMAT (suitable for quoting)
-------------------------------------
    36 of 46 identified restrictions implemented;
    35 with verified clauses; 10 unimplemented (listed below).

    Unimplemented (require retrieval/DB):
      R-DUP-01, R-DUP-02, ...

Also regenerates rules/coverage.md with an up-to-date Markdown table.

USAGE
-----
    PYTHONPATH=. python3 scripts/rule_coverage.py
"""
import json
import sys
from pathlib import Path

# Make sure REGISTRY is populated before we check it
sys.path.insert(0, str(Path(__file__).parent.parent))
from ml.rules.engine import check_all  # noqa: F401 — triggers all @rule imports
from ml.rules.registry import REGISTRY

RULES_JSON = Path("data/rules/rules.json")
COVERAGE_MD = Path("data/rules/coverage.md")

# Must match KNOWN_UNIMPLEMENTED in tests/test_rules.py
KNOWN_UNIMPLEMENTED = {
    "R-DUP-01", "R-DUP-02", "R-DUP-03", "R-DUP-04", "R-DUP-05", "R-DUP-06",
    "R-LEG-01", "R-LEG-02", "R-LEG-03", "R-MED-01",
}


def main():
    with RULES_JSON.open(encoding="utf-8") as f:
        rules: list[dict] = json.load(f)

    total = len(rules)
    implemented_ids = set(REGISTRY.keys())
    verified_count = sum(
        1 for r in rules
        if r["rule_id"] in implemented_ids and r.get("source_clause_verified", False)
    )
    unimplemented = [
        r for r in rules if r["rule_id"] not in implemented_ids
    ]
    truly_missing = [r for r in unimplemented if r["rule_id"] not in KNOWN_UNIMPLEMENTED]

    implemented_count = len(implemented_ids)

    # -----------------------------------------------------------------------
    # Console summary
    # -----------------------------------------------------------------------
    print()
    print("=" * 65)
    print("  RULE COVERAGE SUMMARY")
    print("=" * 65)
    print(
        f"  {implemented_count} of {total} identified restrictions implemented; "
        f"{verified_count} with verified clauses; "
        f"{len(unimplemented)} unimplemented."
    )
    print()

    if unimplemented:
        print("  Unimplemented rules:")
        for r in unimplemented:
            reason = (
                "(requires retrieval/DB stage)" if r["rule_id"] in KNOWN_UNIMPLEMENTED
                else "(NOT in KNOWN_UNIMPLEMENTED — add to checks/ or document reason)"
            )
            print(f"    {r['rule_id']:<14}  {r['name']:<45} {reason}")
    print("=" * 65)
    print()

    if truly_missing:
        print(f"  ⚠ WARNING: {len(truly_missing)} rules not in KNOWN_UNIMPLEMENTED "
              "and not implemented:")
        for r in truly_missing:
            print(f"    {r['rule_id']}: {r['name']}")
        print()

    # -----------------------------------------------------------------------
    # Regenerate rules/coverage.md
    # -----------------------------------------------------------------------
    lines = [
        "# Rules Coverage\n",
        f"Auto-generated by `scripts/rule_coverage.py`.\n",
        f"**Summary:** {implemented_count} of {total} restrictions implemented; "
        f"{verified_count} with verified clauses; {len(unimplemented)} unimplemented.\n",
        "",
        "| Restriction | Rule ID | Implemented | Clause verified | Notes |",
        "|---|---|---|---|---|",
    ]

    for r in rules:
        rid = r["rule_id"]
        implemented = rid in implemented_ids
        verified = r.get("source_clause_verified", False)
        impl_str = "✅ Yes" if implemented else "❌ No"
        ver_str = "✅ Yes" if verified else "⚠️ No"

        if not implemented and rid in KNOWN_UNIMPLEMENTED:
            notes = "Requires retrieval/DB stage — Jai/Divvye"
        elif not implemented:
            notes = "Not yet implemented"
        elif not verified:
            notes = "Unverified — source clause not found in repo document"
        else:
            notes = ""

        lines.append(f"| {r['name']} | {rid} | {impl_str} | {ver_str} | {notes} |")

    lines.append("")
    lines.append("## Unimplemented Rules Detail")
    lines.append("")
    for r in unimplemented:
        lines.append(f"### {r['rule_id']} — {r['name']}")
        lines.append(f"- **Section:** {r.get('section', 'N/A')}")
        lines.append(f"- **Reason not implemented:** {'Retrieval/DB stage' if r['rule_id'] in KNOWN_UNIMPLEMENTED else 'Pending'}")
        lines.append(f"- **Source clause verified:** {r.get('source_clause_verified', False)}")
        lines.append("")

    COVERAGE_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Updated: {COVERAGE_MD}")


if __name__ == "__main__":
    main()
